# Generated by Django 5.2.2 on 2025-06-11 21:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateField(default=apps.users.models.get_current_date),
        ),
    ]
