# Generated by Django 5.2.2 on 2025-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_membership_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ministry',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_ministry',
            field=models.CharField(blank=True, choices=[('PASTORAL', 'Pastoral Care'), ('WORSHIP', 'Worship & Music'), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry'), ('EVANGELISM', 'Evangelism & Outreach'), ('EDUCATION', 'Christian Education'), ('FELLOWSHIP', 'Fellowship & Community'), ('MISSIONS', 'Missions & Service'), ('ADMIN', 'Administration'), ('MEDIA', 'Media & Technology'), ('CHOIR', 'Choir'), ('USHER', 'Ushering'), ('FIN', 'Finance'), ('PRAY', 'Prayer'), ('WOMEN', 'Women'), ('MEN', 'Men'), ('YS', 'Young Singles')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
