# Generated by Django 5.2.2 on 2025-06-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='membership_date',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='phone_number',
        ),
    ]
